### ISSUE TITLE
Consider using a different filename extension than .cfg

### ISSUE THREAD

**Issue by wimglenn** [JonasRudolph/idea-plugin-context-free-grammar#1]
Hi Jonas, 

Many people already use .cfg files as simple configuration files (e.g. `setup.cfg` for Python projects), and this format has been around [forever](https://en.wikipedia.org/wiki/INI_file).  Your plugin now pops up a dialog for these config files for everyone using intellij IDEs, and 99% of the time they won't have anything too do with this "context free grammar" stuff.  

Would you consider registering the plugin with an extension that doesn't collide heavily with existing configuration files?

**Comment by JonasTaulien** [comment]
Hi,
Thanks for creating an issue :)
I was wondering why this Plugin gets so many downloads and already thought about the problem you describe. I concluded by myself, that people read the descriptions of plugins prior to downloading.
Seems like I was wrong about that.
You say, my Plugin pops up in a Dialog - Is it the only Plugin that says, it supports .cfg Files or are there also other Plugins listet in the popup?
I will think about a file extension that is not already in use by a major technology.
Kind regards
Jonas

**Comment by wimglenn** [comment]
The popup looks like this:  

<img width="570" alt="screen shot 2017-11-20 at 11 49 26 pm" src="https://user-images.githubusercontent.com/6615374/33056878-9641be5a-ce4d-11e7-951f-72c2bb6d4287.png">

There are no other plugins listed.

**Comment by JonasTaulien** [comment]
Wow, okay. I understand your issue and will change the extension. Thanks!

**Comment by JonasTaulien** [comment]
Fixed in [Release 0.3.0](https://github.com/JonasRudolph/idea-plugin-context-free-grammar/releases/tag/0.3.0).
Approval from JetBrains needs a few days,
